package com.sfa.model.VO;

import com.sfa.model.base.BaseEntityImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 18 18:40:00 IST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AdminUserRoleassignRowImpl extends ViewRowImpl {


    public static final int ENTITY_ROLEASSIGNMENT = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        UserRoleId,
        UserId,
        RoleId,
        EffecStartDate,
        EffecEndDate,
        SelectedFlag,
        ObjectVersionNumber,
        RoleId1,
        RoleName,
        Isselected,
        Selected;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int USERROLEID = AttributesEnum.UserRoleId.index();
    public static final int USERID = AttributesEnum.UserId.index();
    public static final int ROLEID = AttributesEnum.RoleId.index();
    public static final int EFFECSTARTDATE = AttributesEnum.EffecStartDate.index();
    public static final int EFFECENDDATE = AttributesEnum.EffecEndDate.index();
    public static final int SELECTEDFLAG = AttributesEnum.SelectedFlag.index();
    public static final int OBJECTVERSIONNUMBER = AttributesEnum.ObjectVersionNumber.index();
    public static final int ROLEID1 = AttributesEnum.RoleId1.index();
    public static final int ROLENAME = AttributesEnum.RoleName.index();
    public static final int ISSELECTED = AttributesEnum.Isselected.index();
    public static final int SELECTED = AttributesEnum.Selected.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AdminUserRoleassignRowImpl() {
    }

    /**
     * Gets RoleAssignment entity object.
     * @return the RoleAssignment
     */
    public BaseEntityImpl getRoleAssignment() {
        return (BaseEntityImpl) getEntity(ENTITY_ROLEASSIGNMENT);
    }

    /**
     * Gets the attribute value for USER_ROLE_ID using the alias name UserRoleId.
     * @return the USER_ROLE_ID
     */
    public BigDecimal getUserRoleId() {
        return (BigDecimal) getAttributeInternal(USERROLEID);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_ROLE_ID using the alias name UserRoleId.
     * @param value value to set the USER_ROLE_ID
     */
    public void setUserRoleId(BigDecimal value) {
        setAttributeInternal(USERROLEID, value);
    }

    /**
     * Gets the attribute value for USER_ID using the alias name UserId.
     * @return the USER_ID
     */
    public BigDecimal getUserId() {
        return (BigDecimal) getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_ID using the alias name UserId.
     * @param value value to set the USER_ID
     */
    public void setUserId(BigDecimal value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the attribute value for ROLE_ID using the alias name RoleId.
     * @return the ROLE_ID
     */
    public BigDecimal getRoleId() {
        return (BigDecimal) getAttributeInternal(ROLEID);
    }

    /**
     * Sets <code>value</code> as attribute value for ROLE_ID using the alias name RoleId.
     * @param value value to set the ROLE_ID
     */
    public void setRoleId(BigDecimal value) {
        setAttributeInternal(ROLEID, value);
    }

    /**
     * Gets the attribute value for EFFEC_START_DATE using the alias name EffecStartDate.
     * @return the EFFEC_START_DATE
     */
    public Timestamp getEffecStartDate() {
        return (Timestamp) getAttributeInternal(EFFECSTARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EFFEC_START_DATE using the alias name EffecStartDate.
     * @param value value to set the EFFEC_START_DATE
     */
    public void setEffecStartDate(Timestamp value) {
        setAttributeInternal(EFFECSTARTDATE, value);
    }

    /**
     * Gets the attribute value for EFFEC_END_DATE using the alias name EffecEndDate.
     * @return the EFFEC_END_DATE
     */
    public Timestamp getEffecEndDate() {
        return (Timestamp) getAttributeInternal(EFFECENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EFFEC_END_DATE using the alias name EffecEndDate.
     * @param value value to set the EFFEC_END_DATE
     */
    public void setEffecEndDate(Timestamp value) {
        setAttributeInternal(EFFECENDDATE, value);
    }

    /**
     * Gets the attribute value for SELECTED_FLAG using the alias name SelectedFlag.
     * @return the SELECTED_FLAG
     */
    public String getSelectedFlag() {
        return (String) getAttributeInternal(SELECTEDFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for SELECTED_FLAG using the alias name SelectedFlag.
     * @param value value to set the SELECTED_FLAG
     */
    public void setSelectedFlag(String value) {
        setAttributeInternal(SELECTEDFLAG, value);
    }

    /**
     * Gets the attribute value for OBJECT_VERSION_NUMBER using the alias name ObjectVersionNumber.
     * @return the OBJECT_VERSION_NUMBER
     */
    public Integer getObjectVersionNumber() {
        return (Integer) getAttributeInternal(OBJECTVERSIONNUMBER);
    }

    /**
     * Gets the attribute value for the calculated attribute RoleId1.
     * @return the RoleId1
     */
    public Number getRoleId1() {
        return (Number) getAttributeInternal(ROLEID1);
    }

    /**
     * Gets the attribute value for the calculated attribute RoleName.
     * @return the RoleName
     */
    public String getRoleName() {
        return (String) getAttributeInternal(ROLENAME);
    }

    /**
     * Gets the attribute value for the calculated attribute Isselected.
     * @return the Isselected
     */
    public String getIsselected() {
        return (String) getAttributeInternal(ISSELECTED);
    }

    /**
     * Gets the attribute value for the calculated attribute Selected.
     * @return the Selected
     */
    public Boolean getSelected() {
        return (Boolean) getAttributeInternal(SELECTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Selected.
     * @param value value to set the  Selected
     */
    public void setSelected(Boolean value) {
        if(value!=null && value){
                   setSelectedFlag("true");
               }
               else{
                   setSelectedFlag("false");
               }
               System.out.println("<<<<<<<<<"+getSelectedFlag());


    }
}

