package com.sfa.model.VO;

import com.sfa.model.entity.CustomerContactsImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 03 19:50:36 IST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CustomerContactsViewRowImpl extends ViewRowImpl {
    public static final int ENTITY_CUSTOMERCONTACTS = 0;
    public static final int ENTITY_CUSTOMERACCOUNT = 1;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ContactName,
        ContactId,
        CustAccountId,
        Title,
        Department,
        Address,
        WorkPhone,
        MobilePhone,
        Email,
        BuyInfluenceLevel,
        IsPrimary,
        CreationDate,
        LastUpdateDate,
        CreatedBy,
        LastUpdatedBy,
        NotesSeqId,
        LastUpdateLogin,
        ObjectVersionNumber,
        AccountName,
        CustAccountId1,
        ObjectVersionNumber1,
        AppointmentInviteesView,
        InteractionTeamView,
        OpportunitiesView,
        OpportunityTeamView,
        TaskTeamView,
        ContactBuyingroleLuView1,
        ContactBuyingroleLuView2,
        BooleanLuView1,
        TitleLuView1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int CONTACTNAME = AttributesEnum.ContactName.index();
    public static final int CONTACTID = AttributesEnum.ContactId.index();
    public static final int CUSTACCOUNTID = AttributesEnum.CustAccountId.index();
    public static final int TITLE = AttributesEnum.Title.index();
    public static final int DEPARTMENT = AttributesEnum.Department.index();
    public static final int ADDRESS = AttributesEnum.Address.index();
    public static final int WORKPHONE = AttributesEnum.WorkPhone.index();
    public static final int MOBILEPHONE = AttributesEnum.MobilePhone.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int BUYINFLUENCELEVEL = AttributesEnum.BuyInfluenceLevel.index();
    public static final int ISPRIMARY = AttributesEnum.IsPrimary.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int NOTESSEQID = AttributesEnum.NotesSeqId.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int OBJECTVERSIONNUMBER = AttributesEnum.ObjectVersionNumber.index();
    public static final int ACCOUNTNAME = AttributesEnum.AccountName.index();
    public static final int CUSTACCOUNTID1 = AttributesEnum.CustAccountId1.index();
    public static final int OBJECTVERSIONNUMBER1 = AttributesEnum.ObjectVersionNumber1.index();
    public static final int APPOINTMENTINVITEESVIEW = AttributesEnum.AppointmentInviteesView.index();
    public static final int INTERACTIONTEAMVIEW = AttributesEnum.InteractionTeamView.index();
    public static final int OPPORTUNITIESVIEW = AttributesEnum.OpportunitiesView.index();
    public static final int OPPORTUNITYTEAMVIEW = AttributesEnum.OpportunityTeamView.index();
    public static final int TASKTEAMVIEW = AttributesEnum.TaskTeamView.index();
    public static final int CONTACTBUYINGROLELUVIEW1 = AttributesEnum.ContactBuyingroleLuView1.index();
    public static final int CONTACTBUYINGROLELUVIEW2 = AttributesEnum.ContactBuyingroleLuView2.index();
    public static final int BOOLEANLUVIEW1 = AttributesEnum.BooleanLuView1.index();
    public static final int TITLELUVIEW1 = AttributesEnum.TitleLuView1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CustomerContactsViewRowImpl() {
    }

    /**
     * Gets CustomerContacts entity object.
     * @return the CustomerContacts
     */
    public CustomerContactsImpl getCustomerContacts() {
        return (CustomerContactsImpl) getEntity(ENTITY_CUSTOMERCONTACTS);
    }

    /**
     * Gets CustomerAccount entity object.
     * @return the CustomerAccount
     */
    public EntityImpl getCustomerAccount() {
        return (EntityImpl) getEntity(ENTITY_CUSTOMERACCOUNT);
    }

    /**
     * Gets the attribute value for CONTACT_NAME using the alias name ContactName.
     * @return the CONTACT_NAME
     */
    public String getContactName() {
        return (String) getAttributeInternal(CONTACTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTACT_NAME using the alias name ContactName.
     * @param value value to set the CONTACT_NAME
     */
    public void setContactName(String value) {
        setAttributeInternal(CONTACTNAME, value);
    }

    /**
     * Gets the attribute value for CONTACT_ID using the alias name ContactId.
     * @return the CONTACT_ID
     */
    public BigDecimal getContactId() {
        return (BigDecimal) getAttributeInternal(CONTACTID);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTACT_ID using the alias name ContactId.
     * @param value value to set the CONTACT_ID
     */
    public void setContactId(BigDecimal value) {
        setAttributeInternal(CONTACTID, value);
    }

    /**
     * Gets the attribute value for CUST_ACCOUNT_ID using the alias name CustAccountId.
     * @return the CUST_ACCOUNT_ID
     */
    public BigDecimal getCustAccountId() {
        return (BigDecimal) getAttributeInternal(CUSTACCOUNTID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUST_ACCOUNT_ID using the alias name CustAccountId.
     * @param value value to set the CUST_ACCOUNT_ID
     */
    public void setCustAccountId(BigDecimal value) {
        setAttributeInternal(CUSTACCOUNTID, value);
    }

    /**
     * Gets the attribute value for TITLE using the alias name Title.
     * @return the TITLE
     */
    public String getTitle() {
        return (String) getAttributeInternal(TITLE);
    }

    /**
     * Sets <code>value</code> as attribute value for TITLE using the alias name Title.
     * @param value value to set the TITLE
     */
    public void setTitle(String value) {
        setAttributeInternal(TITLE, value);
    }

    /**
     * Gets the attribute value for DEPARTMENT using the alias name Department.
     * @return the DEPARTMENT
     */
    public String getDepartment() {
        return (String) getAttributeInternal(DEPARTMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPARTMENT using the alias name Department.
     * @param value value to set the DEPARTMENT
     */
    public void setDepartment(String value) {
        setAttributeInternal(DEPARTMENT, value);
    }

    /**
     * Gets the attribute value for ADDRESS using the alias name Address.
     * @return the ADDRESS
     */
    public String getAddress() {
        return (String) getAttributeInternal(ADDRESS);
    }

    /**
     * Sets <code>value</code> as attribute value for ADDRESS using the alias name Address.
     * @param value value to set the ADDRESS
     */
    public void setAddress(String value) {
        setAttributeInternal(ADDRESS, value);
    }

    /**
     * Gets the attribute value for WORK_PHONE using the alias name WorkPhone.
     * @return the WORK_PHONE
     */
    public String getWorkPhone() {
        return (String) getAttributeInternal(WORKPHONE);
    }

    /**
     * Sets <code>value</code> as attribute value for WORK_PHONE using the alias name WorkPhone.
     * @param value value to set the WORK_PHONE
     */
    public void setWorkPhone(String value) {
        setAttributeInternal(WORKPHONE, value);
    }

    /**
     * Gets the attribute value for MOBILE_PHONE using the alias name MobilePhone.
     * @return the MOBILE_PHONE
     */
    public String getMobilePhone() {
        return (String) getAttributeInternal(MOBILEPHONE);
    }

    /**
     * Sets <code>value</code> as attribute value for MOBILE_PHONE using the alias name MobilePhone.
     * @param value value to set the MOBILE_PHONE
     */
    public void setMobilePhone(String value) {
        setAttributeInternal(MOBILEPHONE, value);
    }

    /**
     * Gets the attribute value for EMAIL using the alias name Email.
     * @return the EMAIL
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as attribute value for EMAIL using the alias name Email.
     * @param value value to set the EMAIL
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for BUY_INFLUENCE_LEVEL using the alias name BuyInfluenceLevel.
     * @return the BUY_INFLUENCE_LEVEL
     */
    public String getBuyInfluenceLevel() {
        return (String) getAttributeInternal(BUYINFLUENCELEVEL);
    }

    /**
     * Sets <code>value</code> as attribute value for BUY_INFLUENCE_LEVEL using the alias name BuyInfluenceLevel.
     * @param value value to set the BUY_INFLUENCE_LEVEL
     */
    public void setBuyInfluenceLevel(String value) {
        setAttributeInternal(BUYINFLUENCELEVEL, value);
    }

    /**
     * Gets the attribute value for IS_PRIMARY using the alias name IsPrimary.
     * @return the IS_PRIMARY
     */
    public String getIsPrimary() {
        return (String) getAttributeInternal(ISPRIMARY);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_PRIMARY using the alias name IsPrimary.
     * @param value value to set the IS_PRIMARY
     */
    public void setIsPrimary(String value) {
        setAttributeInternal(ISPRIMARY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Gets the attribute value for NOTES_SEQ_ID using the alias name NotesSeqId.
     * @return the NOTES_SEQ_ID
     */
    public BigDecimal getNotesSeqId() {
        return (BigDecimal) getAttributeInternal(NOTESSEQID);
    }

    /**
     * Sets <code>value</code> as attribute value for NOTES_SEQ_ID using the alias name NotesSeqId.
     * @param value value to set the NOTES_SEQ_ID
     */
    public void setNotesSeqId(BigDecimal value) {
        setAttributeInternal(NOTESSEQID, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Gets the attribute value for OBJECT_VERSION_NUMBER using the alias name ObjectVersionNumber.
     * @return the OBJECT_VERSION_NUMBER
     */
    public Integer getObjectVersionNumber() {
        return (Integer) getAttributeInternal(OBJECTVERSIONNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJECT_VERSION_NUMBER using the alias name ObjectVersionNumber.
     * @param value value to set the OBJECT_VERSION_NUMBER
     */
    public void setObjectVersionNumber(Integer value) {
        setAttributeInternal(OBJECTVERSIONNUMBER, value);
    }

    /**
     * Gets the attribute value for ACCOUNT_NAME using the alias name AccountName.
     * @return the ACCOUNT_NAME
     */
    public String getAccountName() {
        return (String) getAttributeInternal(ACCOUNTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for ACCOUNT_NAME using the alias name AccountName.
     * @param value value to set the ACCOUNT_NAME
     */
    public void setAccountName(String value) {
        setAttributeInternal(ACCOUNTNAME, value);
    }

    /**
     * Gets the attribute value for CUST_ACCOUNT_ID using the alias name CustAccountId1.
     * @return the CUST_ACCOUNT_ID
     */
    public BigDecimal getCustAccountId1() {
        return (BigDecimal) getAttributeInternal(CUSTACCOUNTID1);
    }

    /**
     * Sets <code>value</code> as attribute value for CUST_ACCOUNT_ID using the alias name CustAccountId1.
     * @param value value to set the CUST_ACCOUNT_ID
     */
    public void setCustAccountId1(BigDecimal value) {
        setAttributeInternal(CUSTACCOUNTID1, value);
    }

    /**
     * Gets the attribute value for OBJECT_VERSION_NUMBER using the alias name ObjectVersionNumber1.
     * @return the OBJECT_VERSION_NUMBER
     */
    public Integer getObjectVersionNumber1() {
        return (Integer) getAttributeInternal(OBJECTVERSIONNUMBER1);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJECT_VERSION_NUMBER using the alias name ObjectVersionNumber1.
     * @param value value to set the OBJECT_VERSION_NUMBER
     */
    public void setObjectVersionNumber1(Integer value) {
        setAttributeInternal(OBJECTVERSIONNUMBER1, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link AppointmentInviteesView.
     */
    public RowIterator getAppointmentInviteesView() {
        return (RowIterator) getAttributeInternal(APPOINTMENTINVITEESVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link InteractionTeamView.
     */
    public RowIterator getInteractionTeamView() {
        return (RowIterator) getAttributeInternal(INTERACTIONTEAMVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link OpportunitiesView.
     */
    public RowIterator getOpportunitiesView() {
        return (RowIterator) getAttributeInternal(OPPORTUNITIESVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link OpportunityTeamView.
     */
    public RowIterator getOpportunityTeamView() {
        return (RowIterator) getAttributeInternal(OPPORTUNITYTEAMVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TaskTeamView.
     */
    public RowIterator getTaskTeamView() {
        return (RowIterator) getAttributeInternal(TASKTEAMVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ContactBuyingroleLuView1.
     */
    public RowSet getContactBuyingroleLuView1() {
        return (RowSet) getAttributeInternal(CONTACTBUYINGROLELUVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ContactBuyingroleLuView2.
     */
    public RowSet getContactBuyingroleLuView2() {
        return (RowSet) getAttributeInternal(CONTACTBUYINGROLELUVIEW2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BooleanLuView1.
     */
    public RowSet getBooleanLuView1() {
        return (RowSet) getAttributeInternal(BOOLEANLUVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TitleLuView1.
     */
    public RowSet getTitleLuView1() {
        return (RowSet) getAttributeInternal(TITLELUVIEW1);
    }
}

