package com.sfa.model.service.common;

import oracle.jbo.ApplicationModule;
import oracle.jbo.domain.BlobDomain;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Mar 09 12:59:46 IST 2014
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void uploadFiletoDB(String fileName, String contentType, BlobDomain blob, String plainText);

    void exceptionHandler();
}

