package com.sfa.model.entity;

import oracle.jbo.server.EntityCache;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Feb 28 14:10:16 IST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CustomerContactsCollImpl extends EntityCache {
    /**
     * This is the default constructor (do not remove).
     */
    public CustomerContactsCollImpl() {
    }
}

