package com.sfa.model.service.client;

import com.sfa.model.service.common.AppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
import oracle.jbo.domain.BlobDomain;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Mar 09 12:59:47 IST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient() {
    }

    public void uploadFiletoDB(String fileName, String contentType, BlobDomain blob) {
        Object _ret = this.riInvokeExportedMethod(this, "uploadFiletoDB", new String[] {
                                                  "java.lang.String", "java.lang.String", "oracle.jbo.domain.BlobDomain"
        }, new Object[] { fileName, contentType, blob });
        return;
    }
}

